//	Header generated by Constructor for Palm OS (R) 1.9a3
//
//	Generated at 9:06:50 AM on Monday, June 09, 2003
//
//	Generated for file: XMatrix.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"XMatrix"
//
//	Palm App Version:		"1.0"


//	Resource: PICT 1008
#define BitmapID1008Bitmap                        1008

//	Resource: PICT 1000
#define BitmapID1000Bitmap                        1000

//	Resource: PICT 1002
#define BitmapID1002Bitmap                        1002

//	Resource: PICT 1011
#define BitmapID1011Bitmap                        1011

//	Resource: PICT 1012
#define BitmapID1012Bitmap                        1012

//	Resource: PICT 1018
#define BitmapID1018Bitmap                        1018

//	Resource: PICT 1020
#define BitmapID1020Bitmap                        1020

//	Resource: PICT 1021
#define BitmapID1021Bitmap                        1021


//	Resource: tbmf 1100
#define BrightBitmapFamily                        1100

//	Resource: tbmf 1000
#define DimBitmapFamily                           1000


//	Resource: taif 1000
#define LargeAppIconAppIconFamily                 1000

//	Resource: taif 1001
#define SmallAppIconAppIconFamily                 1001

