//	Header generated by Constructor for Palm OS¨ 1.6
//
//	Generated at 1:42:13 PM on Tuesday, December 04, 2001
//
//	Generated for file: C:\Documents and Settings\Ricardo Lagos\Desktop\RSA_DEV_ENV\ARM Development Kit\Libraries\CPMDemo\Rsc\CPMDemo.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE FROM CONSTRUCTOR FOR PALM OS¨;
//	- DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"CPM Demo"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainSetDefaultButton                      1001	//(Left Origin = 103, Top Origin = 31, Width = 55, Height = 10, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainProviderMoreButton                    1003	//(Left Origin = 103, Top Origin = 19, Width = 40, Height = 10, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainEncryptButton                         1007	//(Left Origin = 11, Top Origin = 118, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainKeyMoreButton                         1009	//(Left Origin = 103, Top Origin = 71, Width = 40, Height = 10, Usable = 0, Anchor Left = 0, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainGenerateKeyButton                     1010	//(Left Origin = 11, Top Origin = 118, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainImportKeyButton                       1011	//(Left Origin = 11, Top Origin = 136, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainReleaseKeyButton                      1012	//(Left Origin = 81, Top Origin = 118, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainExportKeyButton                       1013	//(Left Origin = 81, Top Origin = 136, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainClearEncryptBufferButton              1015	//(Left Origin = 81, Top Origin = 118, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainDecryptButton                         1016	//(Left Origin = 11, Top Origin = 118, Width = 65, Height = 13, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainEncryptedCheckbox                     1014	//(Left Origin = 13, Top Origin = 137, Width = 55, Height = 12, Usable = 0, Selected = 0, Group ID = 0, Font = Standard)
#define MainEncryptBufferField                    1006	//(Left Origin = 80, Top Origin = 100, Width = 75, Height = 12, Usable = 0, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainDecryptField                          1018	//(Left Origin = 80, Top Origin = 100, Width = 75, Height = 12, Usable = 0, Editable = 0, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainEncryptLabel                          1004	//(Left Origin = 13, Top Origin = 98, Usable = 0, Font = Standard)
#define MainDecryptLabel                          1017	//(Left Origin = 13, Top Origin = 98, Usable = 0, Font = Standard)
#define MainProviderList                          1002	//(Left Origin = 2, Top Origin = 19, Width = 95, Usable = 1, Font = Standard, Visible Items = 2)
#define MainActionList                            1005	//(Left Origin = 2, Top Origin = 45, Width = 95, Usable = 1, Font = Standard, Visible Items = 2)
#define MainKeysList                              1008	//(Left Origin = 2, Top Origin = 71, Width = 95, Usable = 0, Font = Standard, Visible Items = 2)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 23, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define ProviderInfoForm                          1200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 1201)
#define ProviderInfoOKButton                      1201	//(Left Origin = 61, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define ProviderInfoMPCheckbox                    1204	//(Left Origin = 7, Top Origin = 64, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoHWCheckbox                    1205	//(Left Origin = 7, Top Origin = 78, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoHashCheckbox                  1206	//(Left Origin = 7, Top Origin = 92, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoEncryptCheckbox               1207	//(Left Origin = 76, Top Origin = 64, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoDecryptCheckbox               1208	//(Left Origin = 76, Top Origin = 78, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoSignCheckbox                  1209	//(Left Origin = 76, Top Origin = 92, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoVerifyCheckbox                1210	//(Left Origin = 76, Top Origin = 106, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoKeysCheckbox                  1211	//(Left Origin = 7, Top Origin = 106, Width = 65, Height = 12, Usable = 1, Selected = 0, Group ID = 0, Font = Standard)
#define ProviderInfoNameField                     1202	//(Left Origin = 6, Top Origin = 18, Width = 140, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 32, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ProviderInfoDescriptionField              1203	//(Left Origin = 6, Top Origin = 36, Width = 140, Height = 24, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 64, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define ProviderInfoNumAlgsField                  1214	//(Left Origin = 82, Top Origin = 121, Width = 25, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 3, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define ProviderInfoUnnamed1213Label              1213	//(Left Origin = 40, Top Origin = 121, Usable = 1, Font = Standard)

//	Resource: tFRM 1300
#define GenerateKeyForm                           1300	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GenerateKeyOKButton                       1301	//(Left Origin = 32, Top Origin = 138, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GenerateKeyCancelButton                   1302	//(Left Origin = 80, Top Origin = 138, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GenerateKeyKeyDataField                   1303	//(Left Origin = 6, Top Origin = 112, Width = 140, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 20, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define GenerateKeyUnnamed1304Label               1304	//(Left Origin = 6, Top Origin = 99, Usable = 1, Font = Standard)
#define GenerateKeyUnnamed1305Label               1305	//(Left Origin = 5, Top Origin = 22, Usable = 1, Font = Standard)
#define GenerateKeyUnnamed1306Label               1306	//(Left Origin = 7, Top Origin = 61, Usable = 1, Font = Standard)
#define GenerateKeyAlgorithmList                  1309	//(Left Origin = 7, Top Origin = 32, Width = 140, Usable = 0, Font = Standard, Visible Items = 5)
#define GenerateKeyUsageList                      1310	//(Left Origin = 7, Top Origin = 79, Width = 140, Usable = 0, Font = Standard, Visible Items = 5)
#define GenerateKeyTypePopTrigger                 1307	//(Left Origin = 5, Top Origin = 35, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1309)
#define GenerateKeyUsagePopTrigger                1308	//(Left Origin = 6, Top Origin = 73, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Font = Standard, List ID = 1310)

//	Resource: tFRM 1400
#define KeyInfoForm                               1400	//(Left Origin = 2, Top Origin = 82, Width = 156, Height = 76, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define KeyInfoUnnamed1401Button                  1401	//(Left Origin = 61, Top Origin = 61, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define KeyInfoTypeField                          1404	//(Left Origin = 46, Top Origin = 22, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define KeyInfoUsageField                         1405	//(Left Origin = 46, Top Origin = 36, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define KeyInfoUnnamed1402Label                   1402	//(Left Origin = 11, Top Origin = 22, Usable = 1, Font = Standard)
#define KeyInfoUnnamed1403Label                   1403	//(Left Origin = 11, Top Origin = 36, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define LibMissingAlert                           1000
#define LibMissingOK                              0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutStarterApp                1000


//	Resource: PICT 1001
#define Bitmap                                    1001

//	Resource: PICT 1002
#define Bitmap2                                   1002

//	Resource: PICT 1008
#define Bitmap3                                   1008

//	Resource: PICT 1011
#define Bitmap4                                   1011

//	Resource: PICT 1012
#define Bitmap5                                   1012

//	Resource: PICT 1018
#define Bitmap6                                   1018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

