//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 3:30:06 PM on Tuesday, September 02, 2003
//
//	Generated for file: Navigation.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Navigation"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 225, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainNavGadget                             1001	//(Left Origin = 5, Top Origin = 12, Width = 127, Height = 127, Usable = 1)
#define MainXValueGadget                          1002	//(Left Origin = 3, Top Origin = 139, Width = 131, Height = 5, Usable = 1)
#define MainYValueGadget                          1003	//(Left Origin = 132, Top Origin = 10, Width = 5, Height = 131, Usable = 1)
#define MainUnnamed1049Label                      1049	//(Left Origin = 198, Top Origin = 43, Usable = 1, Font = Standard)
#define MainUnnamed1050Label                      1050	//(Left Origin = 200, Top Origin = 89, Usable = 1, Font = Standard)
#define MainUnnamed1051Label                      1051	//(Left Origin = 141, Top Origin = 6, Usable = 1, Font = Standard)
#define MainUnnamed1052Label                      1052	//(Left Origin = 144, Top Origin = 31, Usable = 1, Font = Standard)
#define MainUnnamed1053Label                      1053	//(Left Origin = 146, Top Origin = 78, Usable = 1, Font = Standard)
#define MainUnnamed1054Label                      1054	//(Left Origin = 188, Top Origin = 122, Usable = 1, Font = Standard)
#define MainEventLabel                            1055	//(Left Origin = 0, Top Origin = 149, Usable = 1, Font = Standard)
#define MainLeftTriggerPushButton                 1004	//(Left Origin = 185, Top Origin = 75, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainRightTriggerPushButton                1005	//(Left Origin = 213, Top Origin = 75, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainActionAPushButton                     1006	//(Left Origin = 199, Top Origin = 77, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainActionDPushButton                     1007	//(Left Origin = 187, Top Origin = 89, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainActionCPushButton                     1008	//(Left Origin = 199, Top Origin = 101, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainActionBPushButton                     1009	//(Left Origin = 211, Top Origin = 89, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainNavSelectPushButton                   1010	//(Left Origin = 185, Top Origin = 103, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainButtonFunctionPushButton              1011	//(Left Origin = 213, Top Origin = 103, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainNavUpPushButton                       1012	//(Left Origin = 158, Top Origin = 78, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainNavLeftPushButton                     1013	//(Left Origin = 146, Top Origin = 90, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainNavDownPushButton                     1014	//(Left Origin = 158, Top Origin = 102, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainNavRightPushButton                    1015	//(Left Origin = 170, Top Origin = 90, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define Main8WayUpPushButton                      1016	//(Left Origin = 159, Top Origin = 122, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayUpRightPushButton                 1017	//(Left Origin = 171, Top Origin = 122, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayCenterPushButton                  1018	//(Left Origin = 159, Top Origin = 134, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayRightPushButton                   1019	//(Left Origin = 171, Top Origin = 134, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define MainNavCenterPushButton                   1020	//(Left Origin = 158, Top Origin = 90, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define Main8WayLeftPushButton                    1021	//(Left Origin = 147, Top Origin = 134, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayDownPushButton                    1022	//(Left Origin = 159, Top Origin = 146, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayDownRightPushButton               1023	//(Left Origin = 171, Top Origin = 146, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayDownLeftPushButton                1024	//(Left Origin = 147, Top Origin = 146, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main8WayUpLeftPushButton                  1025	//(Left Origin = 147, Top Origin = 122, Width = 11, Height = 11, Usable = 1, Group ID = 8, Font = Standard)
#define Main4WayUpPushButton                      1026	//(Left Origin = 200, Top Origin = 122, Width = 11, Height = 11, Usable = 1, Group ID = 4, Font = Standard)
#define MainBitRockerUpPushButton                 1027	//(Left Origin = 156, Top Origin = 31, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define Main4WayCenterPushButton                  1028	//(Left Origin = 200, Top Origin = 134, Width = 11, Height = 11, Usable = 1, Group ID = 4, Font = Standard)
#define Main4WayRightPushButton                   1029	//(Left Origin = 212, Top Origin = 134, Width = 11, Height = 11, Usable = 1, Group ID = 4, Font = Standard)
#define Main4WayLeftPushButton                    1030	//(Left Origin = 188, Top Origin = 134, Width = 11, Height = 11, Usable = 1, Group ID = 4, Font = Standard)
#define Main4WayDownPushButton                    1031	//(Left Origin = 200, Top Origin = 146, Width = 11, Height = 11, Usable = 1, Group ID = 4, Font = Standard)
#define MainBitRockerLeftPushButton               1032	//(Left Origin = 144, Top Origin = 43, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitRockerDownPushButton               1033	//(Left Origin = 156, Top Origin = 55, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitRockerRightPushButton              1034	//(Left Origin = 168, Top Origin = 43, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitRockerCenterPushButton             1035	//(Left Origin = 156, Top Origin = 43, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitLeftTriggerPushButton              1036	//(Left Origin = 183, Top Origin = 29, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitRightTriggerPushButton             1037	//(Left Origin = 211, Top Origin = 29, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitActionAPushButton                  1038	//(Left Origin = 197, Top Origin = 31, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitActionDPushButton                  1039	//(Left Origin = 185, Top Origin = 43, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitActionCPushButton                  1040	//(Left Origin = 197, Top Origin = 55, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitActionBPushButton                  1041	//(Left Origin = 209, Top Origin = 43, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitPageUpPushButton                   1042	//(Left Origin = 178, Top Origin = 1, Width = 12, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitFunctionPushButton                 1043	//(Left Origin = 211, Top Origin = 57, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitPageDownPushButton                 1044	//(Left Origin = 178, Top Origin = 13, Width = 12, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitHard2PushButton                    1045	//(Left Origin = 166, Top Origin = 6, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitHard3PushButton                    1046	//(Left Origin = 191, Top Origin = 6, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitHard1PushButton                    1047	//(Left Origin = 154, Top Origin = 6, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainBitHard4PushButton                    1048	//(Left Origin = 203, Top Origin = 6, Width = 11, Height = 11, Usable = 1, Group ID = 0, Font = Standard)
#define MainGroupID                               8
#define MainGroupID2                              4

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 49, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 17, Top Origin = 46, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 49, Top Origin = 115, Usable = 1, Font = Bold)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define NavigationMainMenuBar                     1000


//	Resource: MENU 1100
#define NavigationMenu                            1100
#define NavigationAboutNavigation                 1100


//	Resource: PICT 1001
#define BWIconBitmap                              1001

//	Resource: PICT 1002
#define GrayIconBitmap                            1002

//	Resource: PICT 1008
#define ColorIconBitmap                           1008

//	Resource: PICT 1011
#define BWSmallIconBitmap                         1011

//	Resource: PICT 1012
#define GraySmallIconBitmap                       1012

//	Resource: PICT 1018
#define ColorSmallIconBitmap                      1018

//	Resource: PICT 1028
#define ColorDoubleIconBitmap                     1028

//	Resource: PICT 2000
#define BitmapID2000Bitmap                        2000

//	Resource: PICT 2100
#define BitmapID2100Bitmap                        2100

//	Resource: PICT 2200
#define BitmapID2200Bitmap                        2200


//	Resource: tbmf 2100
#define XIndexBitmapFamily                        2100

//	Resource: tbmf 2200
#define YIndexBitmapFamily                        2200

//	Resource: tbmf 2000
#define CursorBitmapFamily                        2000


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

