//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 9:29:10 AM on Thursday, October 02, 2003
//
//	Generated for file: CompatibleGame.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"CompatibleGame"
//
//	Palm App Version:		"0.9"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainActiveAreaGadget                      1001	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1)


//	Resource: MBAR 1000
#define GameMenuBar                               1000


//	Resource: MENU 1000
#define GameMenu                                  1000
#define GameNew                                   1000
#define GameAbout                                 1002


//	Resource: PICT 2001
#define BitmapID2000Bitmap                        2001

//	Resource: PICT 2000
#define BitmapID2000Bitmap2                       2000


//	Resource: tbmf 2000
#define WaterShallowBitmapFamily                  2000

//	Resource: tbmf 2001
#define WaterDeepBitmapFamily                     2001

