//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 10:01:58 AM on Monday, November 11, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Tic Tac Toe"
//
//	Palm App Version:		"2.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainStartButton                           1004	//(Left Origin = 97, Top Origin = 1, Width = 36, Height = 10, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainCancelButton                          1005	//(Left Origin = 97, Top Origin = 1, Width = 36, Height = 10, Usable = 0, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStatusField                           1002	//(Left Origin = 32, Top Origin = 20, Width = 100, Height = 12, Usable = 1, Editable = 0, Underline = 1, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainGameBoardGadget                       1001	//(Left Origin = 20, Top Origin = 39, Width = 120, Height = 120, Usable = 1)


//	Resource: Talt 1001
#define MissingBtComponentsAlert                  1001
#define MissingBtComponentsOK                     0

//	Resource: Talt 1003
#define GameInProgressAlert                       1003
#define GameInProgressOK                          0

//	Resource: Talt 1004
#define YouWinAlert                               1004
#define YouWinOK                                  0

//	Resource: Talt 1005
#define YouLoseAlert                              1005
#define YouLoseOK                                 0

//	Resource: Talt 1006
#define DrawGameAlert                             1006
#define DrawGameOK                                0

//	Resource: Talt 1007
#define ConfirmGameStartAlert                     1007
#define ConfirmGameStartYes                       0
#define ConfirmGameStartNo                        1


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsStartanewgame                  1000
#define MainOptionsCancelcurrentgame              1001
#define MainOptionsAboutTicTacToe                 1003


//	Resource: tSTL 1000
#define StatusStringList                          1000


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

