//	Header generated by Constructor for Palm OS (R) 1.9a3
//
//	Generated at 9:06:50 AM on Monday, June 09, 2003
//
//	Generated for file: Zing.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"Zing"
//
//	Palm App Version:		"1.0"


#define GoBitmapFamily                            1200
#define GoingBitmapFamily                         1300
#define GoneBitmapFamily                          1400
#define DoBitmapFamily                            1500
#define PlayBitmapFamily                          1600
#define TapwaveBitmapFamily                       1700

