//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 9:13:50 PM on Tuesday, January 27, 2004
//
//	Generated for file: TwMpTest.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"TwMpTest"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 61, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 24, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define InvitationForm                            1200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define InvitationCancelButton                    1202	//(Left Origin = 116, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InvitationStartButton                     1203	//(Left Origin = 74, Top Origin = 141, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define InvitationGameTitleLabel                  1204	//(Left Origin = 37, Top Origin = 15, Usable = 1, Font = Large)
#define InvitationStatusLabel                     1205	//(Left Origin = 3, Top Origin = 140, Usable = 1, Font = Standard)
#define InvitationPlayersTable                    1201	//(Left Origin = 3, Top Origin = 35, Width = 150, Height = 100, Editable = 0, Rows = 7)

//	Resource: tFRM 1300
#define GameForm                                  1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define GameLeaveButton                           1301	//(Left Origin = 59, Top Origin = 142, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define GameGameLabel                             1302	//(Left Origin = 4, Top Origin = 25, Usable = 1, Font = Large)
#define GameLeavingGameLabel                      1303	//(Left Origin = 45, Top Origin = 142, Usable = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1000
#define ExceededMaximumLinksAlert                 1000
#define ExceededMaximumLinksOK                    0

//	Resource: Talt 1100
#define InvitationDialogAlert                     1100
#define InvitationDialogYes                       0
#define InvitationDialogNo                        1


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutTwMpTest                  1000

//	Resource: MENU 1200
#define TwMpMenu                                  1200
#define TwMpHost                                  1200


//	Resource: tSTR 1400
#define InvitationStartString                     1400	// "Starting Game..."

//	Resource: tSTR 1300
#define InvitationCancelString                    1300	// "Cancelling..."

//	Resource: tSTR 1200
#define GameHostString                            1200	// "I am the Host"

//	Resource: tSTR 1100
#define GameGuestString                           1100	// "I am Guest"

//	Resource: tSTR 1000
#define GenericPlayerString                       1000	// "Player"


//	Resource: tSTL 1000
#define DeviceStatesStringList                    1000


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

