//	Header generated by Constructor for Palm OS (R) 1.9Xa2
//
//	Generated at 11:11:45 AM on Tuesday, December 3, 2002
//
//	Generated for file: Whiteboard.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"WhiteBoard"
//
//	Palm App Version:		"2.0"


//	Resource: tFRM 1200
#define DrawingForm                               1200	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DrawingAddDevicesButton                   1201	//(Left Origin = 43, Top Origin = 144, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DrawingLeaveButton                        1202	//(Left Origin = 4, Top Origin = 144, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DrawingClearScreenButton                  1203	//(Left Origin = 124, Top Origin = 144, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DrawingToggleLockButton                   1205	//(Left Origin = 83, Top Origin = 144, Width = 35, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DrawingStatusLabel                        1204	//(Left Origin = 6, Top Origin = 132, Usable = 1, Font = Standard)

//	Resource: tFRM 1300
#define MainForm                                  1300	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainConnectButton                         1304	//(Left Origin = 10, Top Origin = 55, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainHostButton                            1307	//(Left Origin = 9, Top Origin = 30, Width = 140, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainStatusLabel                           1305	//(Left Origin = 14, Top Origin = 141, Usable = 1, Font = Standard)


//	Resource: Talt 1000
#define GeneralAlert                              1000
#define GeneralOK                                 0

//	Resource: Talt 1001
#define MissingBtComponentsAlert                  1001
#define MissingBtComponentsOK                     0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutWhiteboard                1000


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

