//	Header generated by Constructor for Palm OS (R) 1.9
//
//	Generated at 9:04:18 AM on Tuesday, September 30, 2003
//
//	Generated for file: HardenedSecurity.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"HardenedSecurity"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define MainGoButton                              1001	//(Left Origin = 88, Top Origin = 137, Width = 48, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainConfigureButton                       1002	//(Left Origin = 22, Top Origin = 137, Width = 48, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0

//	Resource: Talt 1100
#define ErrorAlert                                1100
#define ErrorOK                                   0


//	Resource: tSTR 1007
#define signedstring7String                       1007	// "mjfdrfdxdrfde4ew32q23wsert6yui9oiju7ygfrfcvhjmklokiuhtredserfcvhjhtrdsew4wytvdifdnuxfdx;li"

//	Resource: tSTR 1006
#define signedstring6String                       1006	// ".mk vcc8vc98r5ds5iugngdmpoyfutxdvgytfdsewq2qw345rfgy8uhjikjhygcxdeeszweawszxdrtgcfgyhhui"

//	Resource: tSTR 1005
#define signedstring5String                       1005	// ",.nkdfbuipv xycutftxerrw3r2312qwesxdszxdfgtvbnjjiu87ytrdertyu89oiko9i8uhjm"

//	Resource: tSTR 1004
#define signedstring4String                       1004	// "lksnnvjicvy78ix df trnvc  iohwyy8tgwesn c.llgf7f7io9itfydtguhkgftdyewyr5stdfslr"

//	Resource: tSTR 1003
#define signedstring3String                       1003	// "oi hoadsdsfhoh sfo ihfgijor8y4984t98y5roinonsr lksvrlkrelk f  knsr rl"

//	Resource: tSTR 1002
#define signedstring2String                       1002	// " linfsdfsdf  noprigh r riogf reoighehg9498yy98r13298y3298y232890498r ofi sf,jj,nv, s; w"

//	Resource: tSTR 1001
#define signedstring1String                       1001	// "a.k nd fkab dnoaihgogtfiwb 5tt5g ght87h5t3 p94y862369823r98ty  9pyrg gewrg"

//	Resource: tSTR 1000
#define signedstringString                        1000	// "l;inwpvuribpqht98tgh9733yry2r9gusbdkvnosviusbng8pv7gfwgsgrfihrdgisfsggsgdrgf"


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

