//	Header generated by Constructor for Palm OS (R) 1.8
//
//	Generated at 10:01:41 AM on Monday, November 11, 2002
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"BtPiconet"
//
//	Palm App Version:		"2.0"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainFindAndHostButton                     1001
#define MainJoinButton                            1002
#define MainHostAndWaitButton                     1005
#define MainMasterLabel                           1003
#define MainStatusLabel                           1004
#define MainSlaveLabel                            1006

//	Resource: tFRM 1200
#define ActionForm                                1200
#define ActionLeaveButton                         1201
#define ActionAddButton                           1202
#define ActionLockButton                          1203
#define ActionWhichLabel                          1204
#define ActionSlaveNumbersLabel                   1205
#define ActionStatusLabel                         1206


//	Resource: Talt 1001
#define MissingBtComponentsAlert                  1001
#define MissingBtComponentsOK                     0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsAboutBtPiconet                 1000


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 1501
#define Action1Bitmap                             1501

//	Resource: PICT 1601
#define Action2Bitmap                             1601

//	Resource: PICT 1701
#define Action3Bitmap                             1701

//	Resource: PICT 1801
#define Action4Bitmap                             1801

//	Resource: PICT 1901
#define Action5Bitmap                             1901

//	Resource: PICT 2001
#define Action6Bitmap                             2001

//	Resource: PICT 2101
#define Action7Bitmap                             2101

//	Resource: PICT 2201
#define Action8Bitmap                             2201

//	Resource: PICT 2301
#define Action9Bitmap                             2301

//	Resource: PICT 2401
#define Action10Bitmap                            2401

//	Resource: PICT 2501
#define Action11Bitmap                            2501

//	Resource: PICT 2601
#define Action12Bitmap                            2601

//	Resource: PICT 2701
#define UnknownStateBitmap                        2701

//	Resource: PICT 2801
#define NoLinkBitmap                              2801

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018


//	Resource: tbmf 1500
#define Action1BitmapFamily                       1500

//	Resource: tbmf 1600
#define Action2BitmapFamily                       1600

//	Resource: tbmf 1700
#define Action3BitmapFamily                       1700

//	Resource: tbmf 1800
#define Action4BitmapFamily                       1800

//	Resource: tbmf 1900
#define Action5BitmapFamily                       1900

//	Resource: tbmf 2000
#define Action6BitmapFamily                       2000

//	Resource: tbmf 2100
#define Action7BitmapFamily                       2100

//	Resource: tbmf 2200
#define Action8BitmapFamily                       2200

//	Resource: tbmf 2300
#define Action9BitmapFamily                       2300

//	Resource: tbmf 2400
#define Action10BitmapFamily                      2400

//	Resource: tbmf 2500
#define Action11BitmapFamily                      2500

//	Resource: tbmf 2600
#define Action12BitmapFamily                      2600

//	Resource: tbmf 2700
#define UnknownStateBitmapFamily                  2700

//	Resource: tbmf 2800
#define NoLinkBitmapFamily                        2800


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

