//	Header generated by Constructor for Palm OS (R) 1.9a3
//
//	Generated at 5:28:43 PM on Friday, July 18, 2003
//
//	Generated for file: HighScoreTest.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"HighScoreTest"
//
//	Palm App Version:		"1.0"


//	Resource: tFRM 1000
#define MainForm                                  1000	//(Left Origin = 0, Top Origin = 0, Width = 160, Height = 160, Usable = 1, Modal = 0, Save Behind = 0, Help ID = 0, Menu Bar ID = 1000, Default Button ID = 0)
#define MainNewScoreButton                        1001	//(Left Origin = 123, Top Origin = 146, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainDetailsButton                         1003	//(Left Origin = 82, Top Origin = 146, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainUnregisterButton                      1006	//(Left Origin = 41, Top Origin = 146, Width = 36, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainGetButton                             1014	//(Left Origin = 136, Top Origin = 28, Width = 22, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainRegisterButton                        1019	//(Left Origin = 1, Top Origin = 146, Width = 35, Height = 13, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define MainReportToServerCheckbox                1002	//(Left Origin = 81, Top Origin = 92, Width = 15, Height = 12, Usable = 1, Selected = 1, Group ID = 0, Font = Standard)
#define MainMaxLocalField                         1004	//(Left Origin = 81, Top Origin = 66, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 5, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainMaxServerField                        1005	//(Left Origin = 81, Top Origin = 79, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 5, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainCreatorIDField                        1007	//(Left Origin = 81, Top Origin = 22, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 4, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainScoreTypeField                        1008	//(Left Origin = 81, Top Origin = 35, Width = 50, Height = 12, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 5, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 1)
#define MainLocalSummaryField                     1015	//(Left Origin = 5, Top Origin = 109, Width = 153, Height = 14, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainServerSummaryField                    1016	//(Left Origin = 5, Top Origin = 121, Width = 153, Height = 14, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainGameNameField                         1018	//(Left Origin = 81, Top Origin = 54, Width = 78, Height = 14, Usable = 1, Editable = 1, Underline = 1, Single Line = 1, Dynamic Size = 0, Left Justified = 1, Max Characters = 40, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainServerSyncDateField                   1020	//(Left Origin = 81, Top Origin = 2, Width = 79, Height = 18, Usable = 1, Editable = 0, Underline = 0, Single Line = 1, Dynamic Size = 0, Left Justified = 0, Max Characters = 80, Font = Standard, Auto Shift = 0, Has Scroll Bar = 0, Numeric = 0)
#define MainCreatorIDLabel                        1009	//(Left Origin = 24, Top Origin = 22, Usable = 1, Font = Bold)
#define MainScoreTypeLabel                        1010	//(Left Origin = 22, Top Origin = 35, Usable = 1, Font = Bold)
#define MainMaxLocalLabel                         1011	//(Left Origin = 22, Top Origin = 66, Usable = 1, Font = Bold)
#define MainMaxServerLabel                        1012	//(Left Origin = 15, Top Origin = 79, Usable = 1, Font = Bold)
#define MainReportToServerLabel                   1013	//(Left Origin = 4, Top Origin = 92, Usable = 1, Font = Bold)
#define MainGameNameLabel                         1017	//(Left Origin = 16, Top Origin = 54, Usable = 1, Font = Bold)

//	Resource: tFRM 1100
#define AboutForm                                 1100	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 1, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define AboutOKButton                             1105	//(Left Origin = 58, Top Origin = 133, Width = 40, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define AboutTitleLabel                           1102	//(Left Origin = 38, Top Origin = 23, Usable = 1, Font = Large)
#define AboutText1Label                           1103	//(Left Origin = 16, Top Origin = 54, Usable = 1, Font = Standard)
#define AboutText2Label                           1104	//(Left Origin = 50, Top Origin = 104, Usable = 1, Font = Bold)

//	Resource: tFRM 1200
#define DetailsForm                               1200	//(Left Origin = 2, Top Origin = 2, Width = 156, Height = 156, Usable = 1, Modal = 1, Save Behind = 0, Help ID = 0, Menu Bar ID = 0, Default Button ID = 0)
#define DetailsDoneButton                         1203	//(Left Origin = 5, Top Origin = 139, Width = 36, Height = 12, Usable = 1, Anchor Left = 1, Frame = 1, Non-bold Frame = 1, Font = Standard)
#define DetailsDetailsField                       1201	//(Left Origin = 4, Top Origin = 14, Width = 142, Height = 121, Usable = 1, Editable = 0, Underline = 0, Single Line = 0, Dynamic Size = 0, Left Justified = 1, Max Characters = 0, Font = Standard, Auto Shift = 0, Has Scroll Bar = 1, Numeric = 0)
#define DetailsDetailsScrollBar                   1202	//(Left Origin = 148, Top Origin = 15, Width = 8, Height = 121, Usable = 1, Value = 0, Minimum Value = 0, Maximum Value = 0, Page Size = 0)


//	Resource: Talt 1001
#define RomIncompatibleAlert                      1001
#define RomIncompatibleOK                         0


//	Resource: MBAR 1000
#define MainFormMenuBar                           1000


//	Resource: MENU 1000
#define MainOptionsMenu                           1000
#define MainOptionsEnterTournamentCode            1000
#define MainOptionsAboutHighScoreTest             1001


//	Resource: PICT 1001
#define Largeicon1bitBitmap                       1001

//	Resource: PICT 1002
#define Largeicon2bitBitmap                       1002

//	Resource: PICT 1008
#define Largeicon8bitBitmap                       1008

//	Resource: PICT 1011
#define Smallicon1bitBitmap                       1011

//	Resource: PICT 1012
#define Smallicon2bitBitmap                       1012

//	Resource: PICT 1018
#define Smallicon8bitBitmap                       1018

//	Resource: PICT 21001
#define LargeiconX21bitBitmap                     21001

//	Resource: PICT 21002
#define LargeiconX22bitBitmap                     21002

//	Resource: PICT 21008
#define LargeiconX28bitBitmap                     21008

//	Resource: PICT 21011
#define SmalliconX21bitBitmap                     21011

//	Resource: PICT 21018
#define SmalliconX28bitBitmap                     21018

//	Resource: PICT 21012
#define SmalliconX22bitBitmap                     21012


//	Resource: taif 1000
#define Largeicons12and8bitsAppIconFamily         1000

//	Resource: taif 1001
#define Smallicons12and8bitsAppIconFamily         1001

