//	Header generated by Constructor for Palm OS (R) 1.9a3
//
//	Generated at 11:52:26 PM on Tuesday, April 22, 2003
//
//	Generated for file: FastGame.rsrc
//
//	THIS IS AN AUTOMATICALLY GENERATED HEADER FILE
//	DO NOT EDIT - CHANGES MADE TO THIS FILE WILL BE LOST
//
//	Palm App Name:   		"FastGame"
//
//	Palm App Version:		"0.9"


//	Resource: tFRM 1000
#define MainForm                                  1000
#define MainActiveAreaGadget                      1001


//	Resource: MBAR 1000
#define GameMenuBar                               1000


//	Resource: MENU 1000
#define GameMenu                                  1000
#define GameNew                                   1000
#define GameAbout                                 1002

